export const PRODUCT_ACTIONS = {
  LOADING: "LOADING",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CATEGORIES: "SET_CATEGORIES",
  ERROR: "ERROR",
};

export const FILTER_ACTIONS = {
  CATEGORY: "CATEGORY",
  BRAND: "BRAND",
  RATING: "RATING",
  SORT_BY: "SORT_BY",
  PRICE_RANGE: "PRICE_RANGE",
  CLEAR_FILTERS: "CLEAR_FILTERS",
};

export const WISHLIST_ACTIONS = {
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
};
